const MISSION_BANK=[
{id:'c01',level:1,target:{label:'Mesa',visual:'table',emoji:'🪑'},simple:[{label:'Árvore',visual:'tree',emoji:'🌳'},{label:'Madeira',emoji:'🪵'}],advanced:[{label:'Árvore',visual:'tree',emoji:'🌳'},{label:'Madeira',emoji:'🪵'},{label:'Tábuas',emoji:'🪚'}],note:'A madeira pode ser cortada e montada para formar móveis.'},
{id:'c02',level:1,target:{label:'Camiseta de algodão',visual:'shirt',emoji:'👕'},simple:[{label:'Algodoeiro',visual:'cotton',emoji:'🌿'},{label:'Algodão',visual:'cotton',emoji:'☁️'}],advanced:[{label:'Algodoeiro',visual:'cotton',emoji:'🌿'},{label:'Algodão',visual:'cotton',emoji:'☁️'},{label:'Tecido',emoji:'🧵'}],note:'As fibras do algodão podem virar fios e tecido.'},
{id:'c03',level:1,target:{label:'Garrafa de vidro',visual:'bottle',emoji:'🍾'},simple:[{label:'Areia',visual:'sand',emoji:'🏖️'},{label:'Vidro',emoji:'🔷'}],advanced:[{label:'Areia',visual:'sand',emoji:'🏖️'},{label:'Vidro derretido',emoji:'🔥'},{label:'Vidro moldado',emoji:'🔷'}],note:'A areia rica em sílica participa da fabricação do vidro.'},
{id:'c04',level:1,target:{label:'Pão',visual:'bread',emoji:'🍞'},simple:[{label:'Trigo',emoji:'🌾'},{label:'Farinha',emoji:'🥣'}],advanced:[{label:'Trigo',emoji:'🌾'},{label:'Farinha',emoji:'🥣'},{label:'Massa',emoji:'🫓'}],note:'O trigo é moído para virar farinha e depois massa.'},
{id:'c05',level:1,target:{label:'Queijo',visual:'cheese',emoji:'🧀'},simple:[{label:'Vaca',emoji:'🐄'},{label:'Leite',emoji:'🥛'}],advanced:[{label:'Vaca',emoji:'🐄'},{label:'Leite',emoji:'🥛'},{label:'Coalhada',emoji:'🥣'}],note:'O leite pode passar por transformações até virar queijo.'},
{id:'c06',level:1,target:{label:'Caderno',visual:'notebook',emoji:'📒'},simple:[{label:'Árvore',visual:'tree',emoji:'🌳'},{label:'Papel',emoji:'📄'}],advanced:[{label:'Árvore',visual:'tree',emoji:'🌳'},{label:'Celulose',emoji:'🧻'},{label:'Papel',emoji:'📄'}],note:'A celulose da madeira pode ser transformada em papel.'},

{id:'c07',level:2,target:{label:'Pneu',emoji:'🛞'},simple:[{label:'Seringueira',emoji:'🌳'},{label:'Borracha',emoji:'⬛'}],advanced:[{label:'Seringueira',emoji:'🌳'},{label:'Látex',emoji:'💧'},{label:'Borracha',emoji:'⬛'}],note:'O látex natural pode participar da produção de borracha.'},
{id:'c08',level:2,target:{label:'Tijolo',emoji:'🧱'},simple:[{label:'Argila',emoji:'🟫'},{label:'Barro preparado',emoji:'🟤'}],advanced:[{label:'Argila',emoji:'🟫'},{label:'Barro preparado',emoji:'🟤'},{label:'Peça moldada',emoji:'▰'}],note:'A argila é preparada, moldada e aquecida para formar tijolos.'},
{id:'c09',level:2,target:{label:'Barra de chocolate',emoji:'🍫'},simple:[{label:'Cacaueiro',emoji:'🌳'},{label:'Cacau',emoji:'🫘'}],advanced:[{label:'Cacaueiro',emoji:'🌳'},{label:'Cacau',emoji:'🫘'},{label:'Massa de chocolate',emoji:'🍫'}],note:'As sementes do cacau são processadas para fazer chocolate.'},
{id:'c10',level:2,target:{label:'Blusa de lã',emoji:'🧥'},simple:[{label:'Ovelha',emoji:'🐑'},{label:'Lã',emoji:'🧶'}],advanced:[{label:'Ovelha',emoji:'🐑'},{label:'Lã',emoji:'🧶'},{label:'Fio de lã',emoji:'🧵'}],note:'A lã pode ser fiada e usada para produzir roupas.'},
{id:'c11',level:2,target:{label:'Garrafa plástica',emoji:'🧴'},simple:[{label:'Petróleo',emoji:'🛢️'},{label:'Plástico',emoji:'♻️'}],advanced:[{label:'Petróleo',emoji:'🛢️'},{label:'Plástico',emoji:'♻️'},{label:'Plástico moldado',emoji:'🧴'}],note:'Muitos plásticos são produzidos a partir de derivados do petróleo.'},
{id:'c12',level:2,target:{label:'Livro',emoji:'📘'},simple:[{label:'Árvore',visual:'tree',emoji:'🌳'},{label:'Papel',emoji:'📄'}],advanced:[{label:'Árvore',visual:'tree',emoji:'🌳'},{label:'Celulose',emoji:'🧻'},{label:'Papel',emoji:'📄'}],note:'Folhas de papel podem ser reunidas e encadernadas.'},

{id:'c13',level:3,target:{label:'Tesoura',visual:'scissors',emoji:'✂️'},simple:[{label:'Minério de ferro',visual:'rock',emoji:'🪨'},{label:'Aço',emoji:'🔩'}],advanced:[{label:'Minério de ferro',visual:'rock',emoji:'🪨'},{label:'Aço',emoji:'🔩'},{label:'Lâminas',emoji:'🔪'}],note:'O ferro pode virar aço, usado em ferramentas.'},
{id:'c14',level:3,target:{label:'Lata de alumínio',emoji:'🥫'},simple:[{label:'Bauxita',visual:'rock',emoji:'🪨'},{label:'Alumínio',emoji:'⚙️'}],advanced:[{label:'Bauxita',visual:'rock',emoji:'🪨'},{label:'Alumínio',emoji:'⚙️'},{label:'Chapa de alumínio',emoji:'▭'}],note:'A bauxita é um minério usado na produção de alumínio.'},
{id:'c15',level:3,target:{label:'Óculos',emoji:'👓'},simple:[{label:'Areia rica em sílica',visual:'sand',emoji:'🏖️'},{label:'Vidro',emoji:'🔷'}],advanced:[{label:'Areia rica em sílica',visual:'sand',emoji:'🏖️'},{label:'Vidro',emoji:'🔷'},{label:'Lentes',emoji:'🔍'}],note:'Materiais transparentes podem ser moldados em lentes.'},
{id:'c16',level:3,target:{label:'Cabo elétrico',emoji:'🔌'},simple:[{label:'Minério de cobre',visual:'rock',emoji:'🪨'},{label:'Cobre',emoji:'🟠'}],advanced:[{label:'Minério de cobre',visual:'rock',emoji:'🪨'},{label:'Cobre',emoji:'🟠'},{label:'Fio de cobre',emoji:'➰'}],note:'O cobre conduz eletricidade e pode ser transformado em fios.'},
{id:'c17',level:3,target:{label:'Pote de cerâmica',emoji:'🏺'},simple:[{label:'Argila',emoji:'🟫'},{label:'Cerâmica',emoji:'🏺'}],advanced:[{label:'Argila',emoji:'🟫'},{label:'Barro moldado',emoji:'🟤'},{label:'Cerâmica queimada',emoji:'🏺'}],note:'A argila moldada endurece quando passa por altas temperaturas.'},
{id:'c18',level:3,target:{label:'Caixa de papelão',emoji:'📦'},simple:[{label:'Árvore',visual:'tree',emoji:'🌳'},{label:'Papelão',emoji:'📦'}],advanced:[{label:'Árvore',visual:'tree',emoji:'🌳'},{label:'Celulose',emoji:'🧻'},{label:'Papelão',emoji:'📦'}],note:'Fibras de celulose também podem formar papelão.'},

{id:'c19',level:4,target:{label:'Ponte de concreto',emoji:'🌉'},simple:[{label:'Calcário e argila',visual:'rock',emoji:'🪨'},{label:'Cimento',emoji:'⚪'}],advanced:[{label:'Calcário e argila',visual:'rock',emoji:'🪨'},{label:'Cimento',emoji:'⚪'},{label:'Concreto',emoji:'⬜'}],note:'Cimento, água e agregados podem formar concreto usado em construções.'},
{id:'c20',level:4,target:{label:'Vela',emoji:'🕯️'},simple:[{label:'Petróleo',emoji:'🛢️'},{label:'Parafina',emoji:'⬜'}],advanced:[{label:'Petróleo',emoji:'🛢️'},{label:'Parafina',emoji:'⬜'},{label:'Cera moldada',emoji:'🕯️'}],note:'A parafina é um material usado em muitas velas.'},
{id:'c21',level:4,target:{label:'Janela de vidro',emoji:'🪟'},simple:[{label:'Areia',visual:'sand',emoji:'🏖️'},{label:'Vidro',emoji:'🔷'}],advanced:[{label:'Areia',visual:'sand',emoji:'🏖️'},{label:'Vidro',emoji:'🔷'},{label:'Placa de vidro',emoji:'🪟'}],note:'O vidro pode ser produzido em placas para portas e janelas.'},
{id:'c22',level:4,target:{label:'Colher de metal',emoji:'🥄'},simple:[{label:'Minério de ferro',visual:'rock',emoji:'🪨'},{label:'Aço',emoji:'🔩'}],advanced:[{label:'Minério de ferro',visual:'rock',emoji:'🪨'},{label:'Aço',emoji:'🔩'},{label:'Metal moldado',emoji:'🥄'}],note:'Metais podem ser moldados para produzir utensílios.'},
{id:'c23',level:4,target:{label:'Brinquedo plástico',emoji:'🧸'},simple:[{label:'Petróleo',emoji:'🛢️'},{label:'Plástico',emoji:'♻️'}],advanced:[{label:'Petróleo',emoji:'🛢️'},{label:'Plástico',emoji:'♻️'},{label:'Peças moldadas',emoji:'🧩'}],note:'O plástico pode ser moldado em muitas formas diferentes.'},
{id:'c24',level:4,target:{label:'Cadeira de madeira',emoji:'🪑'},simple:[{label:'Árvore',visual:'tree',emoji:'🌳'},{label:'Madeira',emoji:'🪵'}],advanced:[{label:'Árvore',visual:'tree',emoji:'🌳'},{label:'Madeira',emoji:'🪵'},{label:'Peças de madeira',emoji:'🪚'}],note:'A madeira pode ser cortada e encaixada para formar móveis.'}
];